#配置dev环境
server:
  port: 7070

spring:
  profiles: dev
  #  指定当前微服务对外暴露的名称
  application:
    name: abcms-consumer-depart

eureka:
  client:
    service-url:   #指定Eureka服务注册中心
      defaultZone: http://eureka8400.com:8400/eureka

#开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true

---
#配置test环境
server:
  port: 9090

spring:
  profiles: test
  #  指定当前微服务对外暴露的名称
  application:
    name: abcms-consumer-depart

eureka:
  client:
    service-url:   #指定Eureka服务注册中心
      defaultZone: http://eureka8500.com:8500/eureka

#开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true
