#配置dev环境
server:
  port: 8084

spring:
  profiles: dev
#  指定当前微服务对外暴露的名称
  application:
    name: abcms-provider-depart

#配置spring-data-jpa
  jpa:
    #是否在控制台显示sql语句，默认是false
    show-sql: true
    #应用启动时是否自动建表，默认是false
    generate-ddl: true
    #设置应用启动时，不重新建表
    hibernate:
      ddl-auto: none

#配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://sqy?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/sqy01?autoReconnect=true&failOverReadOnly=false
    username: root
    password: root


eureka:
#  指定eureka服务中心
  client:
    service-url:     #暴露服务中心地址
      defaultZone: http://eureka8400.com:8400/eureka

---

#配置test环境
server:
  port: 8085

spring:
  profiles: test
  #  指定当前微服务对外暴露的名称
  application:
    name: abcms-provider-depart

  #配置spring-data-jpa
  jpa:
    #是否在控制台显示sql语句，默认是false
    show-sql: true
    #应用启动时是否自动建表，默认是false
    generate-ddl: true
    #设置应用启动时，不重新建表
    hibernate:
      ddl-auto: none

  #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://sqy?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/sqy02?autoReconnect=true&failOverReadOnly=false
    username: root
    password: root


eureka:
  #  指定eureka服务中心
  client:
    service-url:     #暴露服务中心地址
      defaultZone: http://eureka8500.com:8500/eureka